### ISSUE TITLE
WeChat app frontend?

### ISSUE THREAD

**Issue by ytrezq** [dicether/frontend#173]
Having watched chineese made games, I was impressed how easy it was for things like Ponzi to attact money (though your case is fair so that should be better) from 200Eth like https://easybooster0888.github.io or more through several millions worth of Ether like https://cn.etherscan.com/address/0x98AD263a95F1ab1AbFF41F4D44b07c3240251A0a#analytics to billions worth of Ether https://www.wofgame.net/ https://cn.etherscan.com/address/0xf8a4d3a0b5859a24cd1320ba014ab17f623612e2#analytics than it was even impossible to even think at such levels in the Western World.

Of course, this was being in contact in the right groups that I learned the existence of those things.

Should you get your frontend working on the China side of wechat or at least translate the website and get it working on Android phones (Firefox mobile can no longer get MetaMask), I would be able to connect you.

**Comment by leroldary** [comment]
Using it on Android should be already possible with TrustWallet or CoinBaseWallet.

We are working on a Chinese translation that hopefully will be available soon.

**Comment by ytrezq** [comment]
@leroldary oh this is for convenience. Everything is more and more centralized and tend to go only one thing which is WeChat. Using an app outside WeChat can act as a stop sign for some peoples (like in the other way you can only pay in some shop using WeChat Pay).

This is not only about translation but using chineese platforms.

Remember china is a country still following mainstream communism 40 years ago so that certains things are not obvious for some peoples outside eastern cities like it would be in the Western world. So like https://wofgame.net you should explain what is Ethereum and provide a step guide and explain why being decentrlized is better.

**Comment by ytrezq** [comment]
Hope to get this before eth value gets something like 60Eth aircut.

@leroldary also, likewise references to the game being anonymous will sound as foreign managed and should be removed from the chineese translation because of the political values there.
